###
# GET health
GET http://20.124.67.46:8001/health

###
GET http://20.231.234.39:8000/health

{"id":"something"}

###
# POST checkout
POST http://20.124.67.46:8001/checkout
content-type: application/json

[10,20,30]

###
# POST order
POST http://20.231.234.39:8000/orders
content-type: application/json

{
    "OrderId": "135",
    "CustomerName": "Linux",
    "Items":[]
}

###
# GET order
GET http://20.231.234.39:8000/orders/eb0fe739-df16-4210-a075-a4a59ad6a8db
