kind: Service
apiVersion: v1
metadata:
  name: checkoutapp
  labels:
    app: checkout
spec:
  selector:
    app: checkout
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutapp
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "checkoutapp"
        dapr.io/app-port: "3001"
    spec:
      containers:
      - name: checkout
        image: avkcontainerregistry.azurecr.io/ordercheckout:v4
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:3001"
        ports:
        - containerPort: 3001
        imagePullPolicy: Always